@file:Suppress("unused")

package dev.itbasis.kochange.core.currency

public object BAM : SealedCurrency(name = "Bosnia-Herzegovina Convertible Mark")
public object BAT : SealedCurrency(name = "Basic Attention Token")
public object BBD : SealedCurrency(name = "Barbadian Dollar")
public object BC : SealedCurrency(name = "BlackCoin", alternatives = listOf("BLK"))
public object BCC : SealedCurrency(name = "BitConnect")
public object BCH : SealedCurrency(name = "BitcoinCash")
public object BCA : SealedCurrency(name = "BitcoinAtom")
public object BLK : SealedCurrency(baseCurrency = BC)
public object BDT : SealedCurrency(name = "Bangladeshi Taka")
public object BGC : SealedCurrency(name = "Aten 'Black Gold' Coin")
public object BGN : SealedCurrency(name = "Bulgarian Lev")
public object BHD : SealedCurrency(name = "Bahraini Dinar")
public object BIF : SealedCurrency(name = "Burundian Franc")
public object BMD : SealedCurrency(name = "Bermudan Dollar")
public object BND : SealedCurrency(name = "Brunei Dollar")
public object BOB : SealedCurrency(name = "Bolivian Boliviano")
public object BRL : SealedCurrency(name = "Brazilian Real", alternatives = listOf("R$"))
public object BRZ : SealedCurrency(name = "Brazilian Digital Token")
public object BSD : SealedCurrency(name = "Bahamian Dollar")
public object BTC : SealedCurrency(name = "Bitcoin", alternatives = listOf("XBT"))
public object BTG : SealedCurrency(name = "Bitcoin Gold")
public object BTN : SealedCurrency(name = "Bhutanese Ngultrum")
public object BWP : SealedCurrency(name = "Botswanan Pula")
public object BYR : SealedCurrency(name = "Belarusian Ruble")
public object BZD : SealedCurrency(name = "Belize Dollar")
public object BNK : SealedCurrency(name = "Bankera Coin")
public object BNB : SealedCurrency(name = "Binance Coin")
public object BTS : SealedCurrency(name = "Bitshare")
public object BHT : SealedCurrency(name = "BHEX Token")
public object BTT : SealedCurrency(name = "BitTorrent")
public object BNT : SealedCurrency(name = "Bancor")
public object BAND : SealedCurrency(name = "Band Protocol")
public object BCD : SealedCurrency(name = "Bitcoin Diamond")
public object BTM : SealedCurrency(name = "Bytom")
public object BSV : SealedCurrency(name = "Bitcoin SV")
public object BUSD : SealedCurrency(name = "Binance USD")
public object BEAM : SealedCurrency(name = "Beam")
