@file:Suppress("unused")

package dev.itbasis.kochange.core.currency

public object ADA : SealedCurrency(name = "Cardano")
public object AE : SealedCurrency(name = "Aeternity")
public object AED : SealedCurrency(name = "United Arab Emirates Dirham")
public object AFN : SealedCurrency(name = "Afghan Afghani")
public object ANT : SealedCurrency(name = "Aragon")
public object ALL : SealedCurrency(name = "Albanian Lek")
public object AMD : SealedCurrency(name = "Armenian Dram")
public object ANC : SealedCurrency(name = "Anoncoin")
public object ANG : SealedCurrency(name = "Netherlands Antillean Guilder")
public object AOA : SealedCurrency(name = "Angolan Kwanza")
public object ARN : SealedCurrency(name = "Aeron")
public object ARS : SealedCurrency(name = "Argentine Peso")
public object ATOM : SealedCurrency(name = "Cosmos")
public object AUD : SealedCurrency(name = "Australian Dollar")
public object AUR : SealedCurrency(name = "Auroracoin")

public object AVT : SealedCurrency(name = "Aventus")
public object AWG : SealedCurrency(name = "Aruban Florin")
public object AZN : SealedCurrency(name = "Azerbaijani Manat")
public object AVA : SealedCurrency(name = "Travala.com")
public object AION : SealedCurrency(name = "Aion")
public object ARK : SealedCurrency(name = "Ark")
public object ANKR : SealedCurrency(name = "Ankr")
public object ALGO : SealedCurrency(name = "Algorand")
public object AMPL : SealedCurrency(name = "Ampleforth")
public object AMP : SealedCurrency(name = "Amp")
public object ARDR : SealedCurrency(name = "Ardor")
public object ABBC : SealedCurrency(name = "ABBC Coin")
public object AAVE : SealedCurrency(name = "Aave")
public object AXS : SealedCurrency(name = "Axie Infinity")
