@file:Suppress("unused")

package dev.itbasis.kochange.core.currency

public object CAD : SealedCurrency(name = "Canadian Dollar")
public object CDF : SealedCurrency(name = "Congolese Franc")
public object CHF : SealedCurrency(name = "Swiss Franc")
public object CLF : SealedCurrency(name = "Chilean Unit of Account (UF)")
public object CLP : SealedCurrency(name = "Chilean Peso")
public object CNC : SealedCurrency(name = "Chinacoin")
public object CNY : SealedCurrency(name = "Chinese Yuan")
public object COP : SealedCurrency(name = "Colombian Peso")
public object CRC : SealedCurrency(name = "Costa Rican Colón")
public object CUP : SealedCurrency(name = "Cuban Peso")
public object CVE : SealedCurrency(name = "Cape Verdean Escudo")
public object CZK : SealedCurrency(name = "Czech Republic Koruna")
public object CND : SealedCurrency(name = "Cindicator")
public object CRO : SealedCurrency(name = "Crypto.com Coin")
public object CEL : SealedCurrency(name = "Celsius")
public object CHSB : SealedCurrency(name = "SwissBorg")
public object CHZ : SealedCurrency(name = "Chiliz")
public object CTXC : SealedCurrency(name = "Cortex")
public object CVT : SealedCurrency(name = "CyberVein")
public object CHR : SealedCurrency(name = "Chromia")
public object CELR : SealedCurrency(name = "Celer Network")
public object CKB : SealedCurrency(name = "Nervos Network")
public object COMP : SealedCurrency(name = "Compound")
public object CRPT : SealedCurrency(name = "Crypterium")
public object COTI : SealedCurrency()
public object CAKE:SealedCurrency(name="PancakeSwap")
