name: checks

on:
  - push
  - pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: download dependencies
        run: ./gradlew :kochange-core:dependencies && du -sch ~/.gradle/caches

      - name: Detekt
        run: ./gradlew detektJvmMain detektJvmTest detektMetadataMain

      - name: tests
        run: ./gradlew check
