name: check

on:
  - push
  - pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'liberica'

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

#      - uses: github/jduimovich/collect-sarif-files@main
#        with:
#          input-file-name: service/build/reports/detekt/detekt.sarif
#          merged-file-name: build/reports/detekt/detekt.sarif
#
#      - uses: github/codeql-action/upload-sarif@master
#        if: ${{ !env.ACT }}
#        with:
#          sarif_file: kochange-core/build/reports/detekt/main.sarif
#          checkout_path: ${{ github.workspace }}
