name: Scan with Detekt

on:
  - push
  - pull_request

jobs:
  Detekt:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'liberica'

      - name: Detekt
        run: ./gradlew detektJvmMain detektJvmTest detektMetadataMain

      - uses: github/codeql-action/upload-sarif@v1
        if: ${{ !env.ACT }}
        with:
          sarif_file: kochange-core/build/reports/detekt/main.sarif
          checkout_path: ${{ github.workspace }}
